config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :users, only: [:show, :index] do
  	resources :follows, only: [:create, :destroy]
	end

  get 'users/:id', to: 'users#show'
  get 'follow_feed', to: 'users#follow_feed'
	
	root 'users#follow_feed' 
	resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ApplicationRecord
	default_scope { order(created_at: :desc) }
	belongs_to :user

	validates :content, presence: true

	after_create_commit { PostBroadcastJob.perform_now self.user, self }
end

app/models/user.rb
class User < ApplicationRecord
	acts_as_followable
	acts_as_follower
  validates :name, presence: true
	has_many :posts
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private
  def after_sign_out_path_for(resource_or_scope)
    users_path
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	 before_action :set_user

	 def create   
    current_user.follow(@user)
    render partial: 'users/follow_user', locals: { user: @user}
  end

  def destroy
    current_user.stop_following(@user)
    render partial: 'users/follow_user', locals: { user: @user}
  end

  def set_user
    @user = User.find(params[:user_id])
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:text)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :bio, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :bio, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index]
	before_action :set_user, only: [:show]
  before_action :set_users, only: [:index, :follow_feed]

  def index
  end

  def show
    @posts = decorate_collection(@user.posts)
  end

  def follow_feed 
    @post = current_user.posts.build
    @posts = decorate_collection(UserVisiblePostsQuery.call(current_user))
  end

  private

  def set_user
    @user = User.find(params[:id])
  end 

  def set_users
    @users = User.all
  end

  def decorate_collection(collection)
    PostDecorator.decorate_collection(collection)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_devise_notifications.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Borat Make A Twitter!', follow_feed_path %>
    </div>
    <ul class="nav navbar-nav"> 
    <li><%= link_to 'View all users', users_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'Your feed', follow_feed_path %></li>
      <li><%= current_user.email %></li>
      <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <li><%= link_to 'Login', new_user_session_path %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prac</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/devise_notifications' %>
		<%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="card gedf-card">
  <div class="card-header">
    Say Something
  </div>
  <div class="card-body">
    <%= simple_form_for @post do |f| %>
      <%= f.input :content %>
      <%= f.button :submit , id: "post_submit"%>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="card gedf-card">
  <div class="card-header">
      <div class="h5 m-0"><%= post.user_name %></div>          
  </div>
  <div class="card-body"> 
    <p class="card-text">
      <%= post.content %>
    </p>
  </div>
</div>

app/views/users/_follow_user.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= button_to("Unfollow #{user.name}", user_follow_path(user.to_param, current_user.get_follow(user).id), :method => :delete, :remote => true) %>
  <% else %>
    <%= button_to("Follow #{user.name}", user_follows_path(user.to_param), :remote => true) %>
  <% end %>
<% end %>

app/views/users/_user_info_card.html.erb
<div class="card">
  <div class="card-body">
    <div class="h5"><%= user.name %></div>
    <div class="h7"><%= user.bio %></div>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <div class="h6 text-muted">Followers</div>
      <div class="h5"><%= user.followers_count %></div>
    </li>
    <li class="list-group-item">
      <div class="h6 text-muted">Following</div>
      <div class="h5"><%= user.follow_count %></div>
    </li>
    <% if user_signed_in? %>    
      <li class="list-group-item">        
        <div id="follow_user">
          <%= render "follow_user", user: user %>
        </div>
      </li>
    <% else %>
      <li>
        <%= link_to 'Sign up', new_user_registration_path %> OR
      </li>      
      <li>
        <%= link_to 'Login', new_user_session_path %> to follow this user.
      </li>      
    <% end %>
  </ul>
</div>

app/views/users/_users_listing.html.erb
<ul class="list-group">
  <li class="list-group-item">Username: <%= link_to user.name, user_path(user) %></li>
  <li class="list-group-item text-muted">Bio: <%= user.bio %></li>
</ul>

app/views/users/follow_feed.html.erb
<div class="container-fluid gedf-wrapper">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info_card', user: current_user %>
    </div>
    <div class="col-md-6 gedf-main">
      <h4>Posts from yourself and others</h4>
      <%= render partial: 'posts/form' %>
      <div id="posts">
        <%= render partial: 'posts/post', collection: @posts, as: :post %>
      </div>
    </div>
    <div class="col-md-3">
      <h4> Users to follow </h4>
      <%= render  partial: 'users_listing', collection: @users, as: :user %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="offset-md-3 col-md-4">
		<h3>People you should get to know</h3>
		<%= render  partial: 'users_listing', collection: @users, as: :user %>
	</div>
</div>

app/views/users/show.html.erb
<h3><%= @user.name %>'s home on the net</h3>
<div class="container-fluid gedf-wrapper">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info_card', user: @user %>
    </div>
    <div class="col-md-6 gedf-main">
      <div id="posts">
        <%= render partial: 'posts/post', collection: @posts, as: :post %>
      </div>
    </div>
  </div>
</div>